services:
  test-memory-server:
    container_name: e2e-scenario1-test-memory-server
  test-env:
    container_name: e2e-scenario1-test-env
    command: ["python3", "-B", "e2e_test/e2e_scenario1.py"]
